### ISSUE TITLE
Error connecting to the broker when used in multiple concurrent build pipelines

### ISSUE THREAD

**Issue by pgaucherand** [gdubya/mqtt-notification-plugin#17]
Mqtt prevents clients from connecting with the same client Id at the same time from the same source IP. 
This plugin set the client Id used to the MqttNotifier class name. In certain situation, if multiple builds running in parallel attempt to connect to the MQTT server at the same time, then the first client will go through but all other will fail.

**Comment by pgaucherand** [comment]
I am happy to fix it myself but I am not sure about the process to contribute here. 
My plan is simply to add a random UUID to the client ID. This would solve the issue.

**Comment by gdubya** [comment]
Hi @pgaucherand,

Thanks for reporting the issue! I've adjusted the cientId to include a random UUID now.  Please try out the latest release and let me know if it helps 👍

**Comment by pgaucherand** [comment]
Fantastic, thank you very much for that. Will check the latest and update here.
