### ISSUE TITLE
Using the plugin from a declarative pipeline

### ISSUE THREAD

**Issue by mountaindude** [gdubya/mqtt-notification-plugin#8]
Hi,

Great plugin, good work.
Trying to use it from a Jenkins (declarative) pipeline, using a Jenkinsfile rather than from the Jenkins UI. 
Can't get it to work though. 
Any suggestions on how to use the plugin from a Jenkinsfile, or from a regular groovy script (which can also be used in Jenkinsfiles)?

Thanks!

**Comment by gdubya** [comment]
Hi @mountaindude,
Apologies for not replying to you sooner. It's probably too late to help you, but have you tried this since #8 was included?

**Comment by mountaindude** [comment]
Hey,

indeed, long time since I worked on this. Barely remember what it was about... Anyways, I have since moved on to using Drone.io for these kind of tasks, so not an issue for me anymore. Thanks anyway!

**Comment by gdubya** [comment]
Ok, i'll close this issue for now. I'm not actually using this feature myself either but if someone else reports it then I'll have another look later.
